language: rust

rust:
  - nightly

cache: cargo

services:
  - postgresql

before_install:
  - sudo apt-get update -yqq
  - sudo apt-get install -yqq libpq-dev

env:
  - MIGRATION_DIR=migrations        FEATURES=postgres DATABASE_URL=postgres://postgres@localhost/rustodon
  - MIGRATION_DIR=migrations_sqlite FEATURES=sqlite   DATABASE_URL=rustodon.sqlite3

before_script:
  - which cargo-install-update || cargo install cargo-update
  - cargo install-update -i diesel_cli
  - cargo install --force rustfmt-nightly

script:
  - cargo fmt -- --write-mode=diff
  - diesel database setup --migration-dir=${MIGRATION_DIR}
  - cargo build --release
