[package]
name = "rustodon"
version = "0.1.0"
authors = ["The Rustodon team"]

[workspace]
members = ['database/', 'lib/resopt/']

[dependencies]
chrono = "0.4"
dotenv = "0.10"
failure = "0.1.1"
failure_derive = "0.1.1"
lazy_static = "1.0"
itertools = "0.7.4"
resopt = { path = "lib/resopt/" }

rocket = "0.3.8"
rocket_codegen = "0.3.8"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
# TODO: switch this back to a normal dep when https://github.com/Keats/validator/pull/46 is merged
# and there's a new release.
validator = { git = "https://github.com/rustodon/validator.git", branch = "fix_path_parsing_regex" }
validator_derive = { git = "https://github.com/rustodon/validator.git", branch = "fix_path_parsing_regex" }

[dependencies.rustodon_database]
path = "database/"

[dependencies.rocket_contrib]
version = "0.3.8"
default-features = false
features = ["json"]

# TODO: switch this back to a normal dep when https://github.com/lfairy/maud/pull/122 is merged
# and there's a new release.
[dependencies.maud]
git = "https://github.com/anxiousmodernman/maud.git"
branch = "121_proc_macro"
features = ["rocket"]

[dev-dependencies]
clippy = ">= 0"

