[package]
name = "rustodon"
version = "0.1.0"
authors = ["The Rustodon team"]

[workspace]
members = ['database/', 'lib/resopt/']

[dependencies]
chrono = "0.4"
dotenv = "0.10"
failure = "0.1.1"
failure_derive = "0.1.1"
lazy_static = "1.0"
itertools = "0.7.4"
resopt = { path = "lib/resopt/" }
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "v0.3" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket", branch = "v0.3" }

diesel = { version = "1.0.0", features = ["postgres", "chrono"] }
r2d2 = "0.8.1"
r2d2-diesel = "1.0.0"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.rustodon_database]
path = "database/"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
branch = "v0.3"
default-features = false
features = ["json", "tera_templates"]

[dev-dependencies]
clippy = ">= 0"

[patch.crates-io]
ring = { git = "https://github.com/SergioBenitez/ring", branch = "v0.11" }
