[package]
name = "rustodon"
version = "0.1.0"
authors = ["Erin <erin@hashbang.sh>"]

[dependencies]
dotenv = "0.10"
try_opt = "0.1"
lazy_static = "1.0"

rocket = "0.3.4"
rocket_codegen = "0.3.4"

diesel = { version = "1.0.0-beta1", features = ["postgres"] }
diesel_infer_schema = { version = "1.0.0-beta1", features = ["postgres"] }
r2d2 = "0.8.1"
r2d2-diesel = "1.0.0-beta1"

pwhash = "0.1.2"

serde = "1.0"
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.3.4"
default-features = false
features = ["json", "tera_templates"]
