[package]
name = "rustodon_database"
version = "0.1.0"
authors = ["The Rustodon team"]

[dependencies]
lazy_static = "1.0"
regex = "0.2"
maplit = "1.0"

diesel = { version = "1.0.0", features = ["postgres", "chrono"] }
diesel_infer_schema = { version = "1.0.0", features = ["postgres"] }
flaken = "0.2.2"
r2d2 = "0.8.1"
r2d2-diesel = "1.0.0"

rocket = "0.3.10"

pwhash = "0.1.2"
chrono = "0.4"
chrono-humanize = "0.0.11"

resopt = { path = "../lib/resopt/" }
