[package]
name = "rustodon_database"
version = "0.1.0"
authors = ["The Rustodon team"]

[features]
postgres = ["diesel/postgres", "diesel_infer_schema/postgres"]
sqlite = ["diesel/sqlite", "diesel_infer_schema/sqlite"]

[dependencies]
lazy_static = "1.0"

diesel = { version = "1.0.0", features = ["chrono"] }
diesel_infer_schema = { version = "1.0.0" }
r2d2 = "0.8.1"
r2d2-diesel = "1.0.0"

rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "v0.3" }

pwhash = "0.1.2"
chrono = "0.4"

resopt = { path = "../lib/resopt/" }
